import { complete, createEntity, deleteEntity, reparent, reopen, reschedule, schedule, updateEntity, type PathCommandDependencies, type PathCommandRejection, type PathCommandResult } from '../domain/path/commands.ts';
import type { JsonObject, PathStatus, PlannedPeriod, ZonedInstant } from '../domain/path/model.ts';
import type { PathRepositoryDocument } from '../domain/path/repository.ts';
export interface PathEntityDraft { id:string; title:string; description:string; priority?:'low'|'medium'|'high'; tags:string[]; planned?:PlannedPeriod; parentId?:string; status:PathStatus; extensions:JsonObject }
export interface PathEditorDependencies { updateDocument(updater:(current:PathRepositoryDocument)=>PathRepositoryDocument|undefined|Promise<PathRepositoryDocument|undefined>):Promise<PathRepositoryDocument>; afterPersist(document:PathRepositoryDocument):void|Promise<void>; now():ZonedInstant; createId():string }
export type PathEditorResult={accepted:true;entityId:string;revision:number;replayed:boolean}|{accepted:false;reason:PathCommandRejection};
export interface PathEntityEditor { saveGoal(draft:PathEntityDraft,commandId:string):Promise<PathEditorResult>; saveAction(draft:PathEntityDraft,commandId:string):Promise<PathEditorResult>; archive(entityId:string,commandId:string):Promise<PathEditorResult> }
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const safe=<T>(v:T):T|undefined=>{try{return JSON.parse(JSON.stringify(v)) as T}catch{return undefined}};
export function createPathEntityEditor(d:PathEditorDependencies):PathEntityEditor{
 async function tx(entityId:string,commandId:string,intent:JsonObject,build:(doc:PathRepositoryDocument,deps:(s:string)=>PathCommandDependencies)=>PathRepositoryDocument|PathCommandRejection):Promise<PathEditorResult>{
  if(!commandId.trim())return{accepted:false,reason:'invalid-command'}; const clean=safe(intent);if(!clean)return{accepted:false,reason:'invalid-command'};let out:PathEditorResult|undefined,changed=false;
  const saved=await d.updateDocument(current=>{const prior=current.envelope.events.find(e=>e.extensions.editorCommandId===commandId);if(prior){out=prior.entityId===entityId&&same(prior.extensions.editorIntent,clean)?{accepted:true,entityId,revision:current.envelope.revision,replayed:true}:{accepted:false,reason:'invalid-command'};return}
   const n=current.envelope.events.length,result=build(current,s=>({commandId:`${commandId}:${s}`,now:d.now,createId:d.createId}));if(typeof result==='string'){out={accepted:false,reason:result};return}if(result.envelope.events.length===n){out={accepted:false,reason:'no-op'};return}changed=true;out={accepted:true,entityId,revision:current.envelope.revision,replayed:false};return{...result,envelope:{...result.envelope,events:result.envelope.events.map((e,i)=>i<n?e:{...e,extensions:{...e.extensions,editorCommandId:commandId,editorIntent:clean}})}}});
  if(!out)throw new Error('Path editor transaction did not execute');if(!changed)return out;await d.afterPersist(saved);return{accepted:true,entityId,revision:saved.envelope.revision,replayed:false};
 }
 function saveEntity(type:'goal'|'action',draft:PathEntityDraft,commandId:string){const clean=safe(draft as unknown as JsonObject);if(!clean)return Promise.resolve<PathEditorResult>({accepted:false,reason:'invalid-command'});return tx(draft.id,commandId,{operation:`save-${type}`,draft:clean},(doc,deps)=>{let env=doc.envelope,entity=env.entities.find(e=>e.id===draft.id&&!e.deletedAt);const apply=(r:PathCommandResult)=>{if(!r.accepted)return r.reason;env=r.envelope;entity=r.entity};
   if(!entity){const failure=apply(createEntity(env,{id:draft.id,type,title:draft.title,description:draft.description,...(draft.priority?{priority:draft.priority}:{}),tags:draft.tags,...(draft.parentId?{parentId:draft.parentId}:{}),...(draft.planned?{planned:draft.planned}:{}),extensions:draft.extensions},deps('create')));if(failure)return failure}else{if(entity.type!==type)return'incompatible-type';const patch={title:draft.title,description:draft.description,...(draft.priority?{priority:draft.priority}:{}),tags:draft.tags,extensions:draft.extensions};if(!same({title:entity.title,description:entity.description,priority:entity.priority,tags:entity.tags,extensions:entity.extensions},patch)){const f=apply(updateEntity(env,draft.id,patch,deps('update')));if(f)return f}if(!same(entity?.planned,draft.planned)){if(!draft.planned)return'invalid-command';const f=apply(entity?.planned?reschedule(env,draft.id,draft.planned,deps('planned')):schedule(env,draft.id,draft.planned,deps('planned')));if(f)return f}if(entity?.parentId!==draft.parentId){const f=apply(reparent(env,draft.id,draft.parentId,deps('parent')));if(f)return f}}
   entity=env.entities.find(e=>e.id===draft.id)!;if(entity.status!==draft.status){const r=draft.status==='done'?complete(env,draft.id,deps('status')):entity.status==='done'&&draft.status==='in-progress'?reopen(env,draft.id,deps('status')):undefined;if(!r)return'incompatible-type';const f=apply(r);if(f)return f}return{...doc,envelope:env}})}
 return{saveGoal:(x,c)=>saveEntity('goal',x,c),saveAction:(x,c)=>saveEntity('action',x,c),archive:(id,c)=>tx(id,c,{operation:'archive',entityId:id},(doc,deps)=>{const r=deleteEntity(doc.envelope,id,deps('archive'));return r.accepted?{...doc,envelope:r.envelope}:r.reason})};
}
