packages:
  - 'obsidian_plugin'
  - 'chrome_extension'
  - 'windows_app'
  - 'android_app'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  spawn-sync: true
  unrs-resolver: true
  vue-demi: true
