/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeModal: typeof import('./../components/AddNodeModal.vue')['default']
    Changelog: typeof import('./../components/Changelog.vue')['default']
    GridItem: typeof import('./../components/vue-grid-layout/GridItem.vue')['default']
    GridLayout: typeof import('./../components/vue-grid-layout/GridLayout.vue')['default']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    IHeroiconsArrowPath: typeof import('~icons/heroicons/arrow-path')['default']
    IHeroiconsBookmark20Solid: typeof import('~icons/heroicons/bookmark20-solid')['default']
    IHeroiconsDocumentText20Solid: typeof import('~icons/heroicons/document-text20-solid')['default']
    IHeroiconsHome20Solid: typeof import('~icons/heroicons/home20-solid')['default']
    'IHeroiconsOutline:menuAlt2': typeof import('~icons/heroicons-outline/menu-alt2')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    IHeroiconsPencil20Solid: typeof import('~icons/heroicons/pencil20-solid')['default']
    IHeroiconsPlusCircle20Solid: typeof import('~icons/heroicons/plus-circle20-solid')['default']
    Install: typeof import('./../components/install.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../components/Settings.vue')['default']
    TreeNode: typeof import('./../components/vue-tree-dnd-main/TreeNode.vue')['default']
    TreeNodeContent: typeof import('./../components/TreeNodeContent.vue')['default']
    Update: typeof import('./../components/update.vue')['default']
    VueTreeDnd: typeof import('./../components/vue-tree-dnd-main/VueTreeDnd.vue')['default']
  }
}
